services:
  app:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: a22adrmacfir_admin
      DB_PASS: Projecte0-AdrianMaciel
      DB_NAME: a22adrmacfir_proj0

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_bd
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
